---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: importing the variables
      include_vars: vars/bastion_setup

    - name: importing variables
      include_vars: vars/output_vars

    - name: creating ec2 key
      amazon.aws.ec2_key:
        name: bastion
        region: "{{region}}"
      register: bastion_key
    
    - name: storing the key
      copy:
        content: "{{bastion_key.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: bastion_key.changed

    - name: creatinng the security group
      amazon.aws.ec2_security_group:
        name: bastion-sg
        description: This is the security group for bastion server
        vpc_id: vpc-0fc45ee16e87b9e79
        region: "{{region}}"
        rules: 
          - proto: ssh
            from_port: 22
            to_port: 22
            cidr_ip: 192.140.155.214/32
      register: bastion_out

    - name: creating bastion instance
      amazon.aws.ec2_instance:
        name: "bastion-instance"
        key_name: bastion
        region: "{{region}}"
        instance_type: t2.micro
        wait: yes
        exact_count: 1
        security_group: "{{bastion_out.group_id}}"
        image_id: "{{bastion_ami}}"
      register: bastionhost_out
      
