---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: importing variables
      include_vars: vars/vpc_setup

    - name: creating vpc
      amazon.aws.ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_Cidr}}"
        region: "{{region}}"
        dns_hostnames: True
        dns_support: True
        tenancy: "default"
        state: present
      register: vpcout
    
    - name: printing the vpcout
      debug:
        var: vpcout
    
    - name: Create public-subnet
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{pubsub1}}"
        region: "{{region}}"
        az: "{{zone1}}"
        map_public: True
        tags:
          Name: vprofile-pubsub1
      register: pubsub1_out

    - name: Create public-subnet
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{pubsub2}}"
        region: "{{region}}"
        az: "{{zone2}}"
        map_public: True
        tags:
          Name: vprofile-pubsub2
      register: pubsub2_out

    - name: Create public-subnet
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{pubsub3}}"
        region: "{{region}}"
        az: "{{zone3}}"
        map_public: True
        tags:
          Name: vprofile-pubsub3
      register: pubsub3_out

    - name: Create pirvate-subnet 
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{pirsub1}}"
        region: "{{region}}"
        az: "{{zone1}}"
        map_public: True
        tags:
          Name: vprofile-pirsub1
      register: pirsub1_out
    
    - name: Create pirvate-subnet 
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{pirsub2}}"
        region: "{{region}}"
        az: "{{zone2}}"
        map_public: True
        tags:
          Name: vprofile-pirsub2
      register: pirsub2_out

    - name: Create pirvate-subnet 
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{pirsub3}}"
        region: "{{region}}"
        az: "{{zone3}}"
        map_public: True
        tags:
          Name: vprofile-pirsub3
      register: pirsub3_out

    - name: Create Internet gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        tags:
          Name: vprofile-igw
      register: igw

    - name: Create route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: Vprofile-pubRT
        subnets:
          - "{{ pubsub1_out.subnet.id }}"
          - "{{ pubsub2_out.subnet.id }}"
          - "{{ pubsub3_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
      register: pubout_RT
    
    - name: Create new nat gateway and allocate new EIP if a nat gateway does not yet exist in the subnet.
      amazon.aws.ec2_vpc_nat_gateway:
        state: present
        subnet_id: "{{ pubsub1_out.subnet.id }}"
        wait: true
        region: "{{region}}"
        if_exist_do_not_create: true
      register: new_nat_gateway

    - name: Create private route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: Vprofile-pirvateRT
        subnets:
          - "{{ pirsub1_out.subnet.id }}"
          - "{{ pirsub2_out.subnet.id }}"
          - "{{ pirsub3_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ new_nat_gateway.nat_gateway_id }}"
      register: pirout_RT


    - name: printing the variables
      debug:
        var: "{{item}}"
      loop:
        - vpcout.vpc.id
        - pubsub1_out.subnet.id
        - pubsub2_out.subnet.id
        - pubsub3_out.subnet.idpubsub3_out.subnet.id
        - pirsub1_out.subnet.id
        - pirsub2_out.subnet.id
        - pirsub3_out.subnet.id
        - igw.gateway_id
        - new_nat_gateway.nat_gateway_id
        - pubout_RT.route_table_id
        - pirout_RT.route_table_id
    - ansible.builtin.set_fact:
        vpcid: "{{vpcout.vpc.id}}"
        pubsub1id: "{{pubsub1_out.subnet.id}}"
        pubsub2id: "{{pubsub2_out.subnet.id}}"
        pubsub3id: "{{pubsub3_out.subnet.id}}"
        pirsub1id: "{{pirsub1_out.subnet.id}}"
        pirsub2id: "{{pirsub2_out.subnet.id}}"
        pirsub3id: "{{pirsub3_out.subnet.id}}" 
        igwid: "{{igw.gateway_id}}"
        ngwid: "{{new_nat_gateway.nat_gateway_id}}"
        puboutid: "{{pubout_RT.route_table_id}}"
        piroutid: "{{pirout_RT.route_table_id}}"
        cacheable: yes

    - name: creating variable file for vpc pirsub1_out
      copy: 
        content: "vpcid: {{vpcout.vpc.id}}\npubsub1id: {{pubsub1_out.subnet.id}}\npubsub2id: {{pubsub2_out.subnet.id}}\npubsub3id: {{pubsub3_out.subnet.id}}\npirsub1id: {{pirsub1_out.subnet.id}}\npirsub2id: {{pirsub2_out.subnet.id}}\npirsub3id: {{pirsub3_out.subnet.id}}\nigwid: {{igw.gateway_id}}\nngwid: {{new_nat_gateway.nat_gateway_id}}\npuboutid: {{pubout_RT.route_table_id}}\npiroutid: {{pirout_RT.route_table_id}}"
        dest: vars/vpc_output_vars