---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: importing variables
      include_vars: vars/vpc_setup
    
    - name: Create public-subnet
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: vpc-0fc45ee16e87b9e79
        cidr: "{{pubsub1}}"
        region: "{{region}}"
        az: "{{zone1}}"
        map_public: True
        tags:
          Name: vprofile-pubsub1
      register: pubsub1_out

    - name: Create public-subnet
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: vpc-0fc45ee16e87b9e79
        cidr: "{{pubsub2}}"
        region: "{{region}}"
        az: "{{zone2}}"
        map_public: True
        tags:
          Name: vprofile-pubsub2
      register: pubsub2_out

    - name: Create public-subnet
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: vpc-0fc45ee16e87b9e79
        cidr: "{{pubsub3}}"
        region: "{{region}}"
        az: "{{zone3}}"
        map_public: True
        tags:
          Name: vprofile-pubsub3
      register: pubsub3_out

    - name: Create pirvate-subnet 
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: vpc-0fc45ee16e87b9e79
        cidr: "{{pirsub1}}"
        region: "{{region}}"
        az: "{{zone1}}"
        map_public: True
        tags:
          Name: vprofile-pirsub1
      register: pirsub1_out
    
    - name: Create pirvate-subnet 
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: vpc-0fc45ee16e87b9e79
        cidr: "{{pirsub2}}"
        region: "{{region}}"
        az: "{{zone2}}"
        map_public: True
        tags:
          Name: vprofile-pirsub2
      register: pirsub2_out

    - name: Create pirvate-subnet 
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: vpc-0fc45ee16e87b9e79
        cidr: "{{pirsub3}}"
        region: "{{region}}"
        az: "{{zone3}}"
        map_public: True
        tags:
          Name: vprofile-pirsub3
      register: pirsub3_out

    - name: Create Internet gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: vpc-0fc45ee16e87b9e79
        region: "{{region}}"
        state: present
        tags:
          Name: vprofile-igw
      register: igw

    - name: Create VPC gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: vpc-0fc45ee16e87b9e79
        region: "{{region}}"
        tags:
          Name: Vprofile-pubRT
        subnets:
          - "{{ pubsub1_out.subnet.id }}"
          - "{{ pubsub2_out.subnet.id }}"
          - "{{ pubsub3_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw-0475271c4c5e5f2f6 }}"
      register: pubout_RT